name: (Compiler) Publish Prereleases Nightly
'on':
  - push
  - pull_request
permissions: {}
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
jobs:
  publish_prerelease_experimental:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Publish to Experimental channel
