name: React Compiler (Rust)
'on':
  - push
  - pull_request
permissions: {}
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
    name: Tests
