name: (Compiler) TypeScript
'on':
  - push
  - pull_request
permissions: {}
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
jobs:
  discover_yarn_workspaces:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
    name: Discover yarn workspaces
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
    name: Lint babel-plugin-react-compiler
  jest:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
    name: Jest babel-plugin-react-compiler
  test:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
    name: Test ${{ matrix.workspace_name }}
