name: (DevTools) Discord Notify
'on':
  - push
  - pull_request
permissions: {}
jobs:
  check_access:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  check_maintainer:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
