name: (DevTools) Regression Tests
'on':
  - push
  - pull_request
permissions: {}
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
jobs:
  download_build:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Download base build
  build_devtools_and_process_artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Build DevTools and process artifacts
  run_devtools_tests_for_versions:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Run DevTools tests for versions
  run_devtools_e2e_tests_for_versions:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Run DevTools e2e tests for versions
