name: (Runtime) ESLint Plugin E2E
'on':
  - push
  - pull_request
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: ESLint v${{ matrix.eslint_major }}
