name: (Runtime) Release From CI
'on':
  - push
  - pull_request
permissions: {}
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
jobs:
  resolve:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Resolve release inputs
  notify_starting:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Notify Discord (release starting)
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Publish release
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Notify Discord on failure
