name: (Runtime) Fuzz tests
'on':
  - push
  - pull_request
permissions: {}
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
jobs:
  test_fuzz:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
