name: (Runtime) Commit Artifacts for Meta WWW and fbsource V2
'on':
  - push
  - pull_request
permissions: {}
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
jobs:
  download_artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
  process_artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
  commit_www_artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
  commit_fbsource_artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
