name: (Shared) Label Core Team PRs
'on':
  - push
  - pull_request
permissions: {}
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
jobs:
  check_access:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  check_maintainer:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  label:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
