name: (Shared) Lint
'on':
  - push
  - pull_request
permissions: {}
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
    name: Run prettier
  eslint:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
    name: Run eslint
  check_license:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
    name: Check license
  test_print_warnings:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        working-directory: /tmp
    name: Test print warnings
