name: (Shared) Lint
'on':
  - push
  - pull_request
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Run prettier
  eslint:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Run eslint
  check_license:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Check license
  test_print_warnings:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    name: Test print warnings
