name: (Shared) Check maintainer
'on':
  - push
  - pull_request
permissions: {}
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
jobs:
  check_maintainer:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
