name: (Shared) Manage stale issues and PRs
'on':
  - push
  - pull_request
permissions:
  issues: write
  pull-requests: write
env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
